const FAILED_PIPELINE_STATUS = 'failed';
const GENERATED_PIPELINE_STATUS = 'generated';
const WAITING_PIPELINE_STATUS = 'waiting';

module.exports = {
  FAILED_PIPELINE_STATUS,
  GENERATED_PIPELINE_STATUS,
  WAITING_PIPELINE_STATUS,
};
