export const ADD_EXERCISE_EXPRESSION_CHANGE = "ADD_EXERCISE_EXPRESSION_CHANGE"
export const ADD_EXERCISE_RESULT_CHANGE = "ADD_EXERCISE_RESULT_CHANGE"
export const ADD_EXERCISE_GET_RESULT = "ADD_EXERCISE_GET_RESULT"
export const ADD_EXERCISE = "ADD_EXERCISE"